#!/usr/bin/env python3
"""bigquery-cost-lab benchmark runner.

Three ways to use it:

  # 1. Run everything from Python (needs `gcloud auth application-default login`)
  python bench.py run --project MY_PROJECT --phase base     # A-D variants
  bq query --use_legacy_sql=false < sql/run/03_build_mv.sql  # then build the MV
  python bench.py run --project MY_PROJECT --phase mv       # MV + smart-tuning rerun

  # 2. Console only: generate ready-to-paste scripts into sql/run/
  python bench.py emit --shift-years 16     # 16 in the free sandbox, 0 with billing

  # 3. Turn a results CSV (from `run`, or exported from sql/run/05_results.sql) into results.md + chart
  python bench.py report results/results.csv
"""
from __future__ import annotations

import argparse
import csv
import pathlib
import re
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parent
QDIR = ROOT / "sql" / "queries"
TDIR = ROOT / "sql" / "templates"
RUNDIR = ROOT / "sql" / "run"
RESULTS = ROOT / "results"
DATASET = "so_bench"
LAB_LABEL = "bqcl"
PRICE_PER_TIB = 6.25  # on-demand, US multi-region
SANDBOX_SHIFT_YEARS = 16  # see sql/templates/01_build_tables.sql for why


# Files under sql/ are written ready to paste into the sandbox, i.e. already shifted
# +16 years. For any other shift, render_*() moves the values by the difference.
FILE_SHIFT = SANDBOX_SHIFT_YEARS
YEAR_RE = re.compile(r"'(\d{4})(?=-\d\d)")  # quoted date literals: '2036-01-01', '2036-01'


def render_query(sql: str, shift: int) -> str:
    """Move every quoted date literal in a query by (shift - FILE_SHIFT) years."""
    delta = shift - FILE_SHIFT
    return YEAR_RE.sub(lambda m: f"'{int(m.group(1)) + delta}", sql) if delta else sql


def render_template(sql: str, shift: int) -> str:
    """Set the build script's date shift (its source-date filter stays untouched)."""
    return re.sub(r"INTERVAL \d+ YEAR", f"INTERVAL {shift} YEAR", sql)

# Variant key -> table. Order here is the order in every table and chart.
VARIANTS = {
    "a_raw": "so_raw",
    "b_part_day": "so_part_day",
    "c_part_day_clust": "so_part_day_clust",
    "d_part_month_clust": "so_part_month_clust",
}
MV = "mv_daily_tag_counts"
MV_QUERIES = ["q01", "q07"]  # queries the MV can answer
ANTI_PATTERNS = {"q08", "q09"}  # excluded from the headline totals
VARIANT_NAMES = {
    "a_raw": "A: unpartitioned",
    "b_part_day": "B: partitioned (day)",
    "c_part_day_clust": "C: day + clustered",
    "d_part_month_clust": "D: month + clustered",
    "e_mv": "E: materialized view",
    "c_after_mv": "C after MV exists (smart tuning)",
}
COLORS = {  # fixed categorical order, validated for CVD separation
    "a_raw": "#2a78d6",
    "b_part_day": "#eb6834",
    "c_part_day_clust": "#1baf7a",
    "d_part_month_clust": "#eda100",
    "e_mv": "#e87ba4",
}


def queries() -> dict[str, tuple[str, str]]:
    """{'q01': (name, sql_template)} for the base (non-MV) templates."""
    out = {}
    for p in sorted(QDIR.glob("q*.sql")):
        if p.name.endswith(".mv.sql"):
            continue
        out[p.stem[:3]] = (p.stem, p.read_text())
    return out


def mv_query(qid: str) -> str:
    return next(QDIR.glob(f"{qid}_*.mv.sql")).read_text()


def plan(phase: str, shift: int = FILE_SHIFT):
    """Yield (qid, variant, sql) for a phase, with dates rendered for `shift`."""
    for qid, v, sql in _plan(phase):
        yield qid, v, render_query(sql, shift)


# Base queries name one example table (e.g. `so_bench.so_part_day`) so they run as-is;
# the benchmark swaps that name for each variant's table.
TABLE_RE = re.compile(rf"`{DATASET}\.so_\w+`")


def on_table(sql: str, table: str) -> str:
    """Point every base-table reference in `sql` at `table`."""
    return TABLE_RE.sub(f"`{DATASET}.{table}`", sql)


def _plan(phase: str):
    qs = queries()
    if phase == "base":
        for qid, (_, tpl) in qs.items():
            for v, table in VARIANTS.items():
                yield qid, v, on_table(tpl, table)
    elif phase == "mv":
        for qid in MV_QUERIES:
            yield qid, "e_mv", mv_query(qid)
            yield qid, "c_after_mv", on_table(qs[qid][1], VARIANTS["c_part_day_clust"])
    else:
        raise ValueError(phase)


# --------------------------------------------------------------------------- emit
def emit(shift: int) -> None:
    """Write ready-to-paste scripts for BigQuery Studio into sql/run/."""
    RUNDIR.mkdir(exist_ok=True)
    head = (f"-- GENERATED by `python bench.py emit --shift-years {shift}` - edit sql/templates or\n"
            f"-- sql/queries instead. Dates are shifted +{shift} years"
            + (" (sandbox mode)." if shift else ".") + "\n")
    for name in ("01_build_tables.sql", "03_build_mv.sql", "05_results.sql"):
        (RUNDIR / name).write_text(head + render_template((TDIR / name).read_text(), shift))
    for phase, fname in (("base", "02_benchmark.sql"), ("mv", "04_benchmark_mv.sql")):
        parts = [head +
                 f"-- Phase: {phase}. Paste into BigQuery Studio and run as one script.\n"
                 f"-- Each statement is labelled via @@query_label so 05_results.sql can find it.\n"]
        for qid, v, sql in plan(phase, shift):
            body = sql.strip().rstrip(";")
            parts.append(f"SET @@query_label = 'lab:{LAB_LABEL},q:{qid},v:{v}';\n{body};\n")
        (RUNDIR / fname).write_text("\n".join(parts))
    print(f"wrote sql/run/ (shift={shift})")


# --------------------------------------------------------------------------- run
def run(project: str, phase: str, max_gb: float, dry_run: bool, shift: int) -> None:
    from google.cloud import bigquery  # imported lazily so `emit`/`report` need no GCP libs

    client = bigquery.Client(project=project, location="US")
    RESULTS.mkdir(exist_ok=True)
    out_path = RESULTS / "results.csv"
    rows = list(csv.DictReader(out_path.open())) if out_path.exists() else []
    rows = [r for r in rows if (r["query"], r["variant"]) not in
            {(q, v) for q, v, _ in plan(phase, shift)}]

    for qid, v, sql in plan(phase, shift):
        cfg = bigquery.QueryJobConfig(
            use_query_cache=False,
            dry_run=dry_run,
            maximum_bytes_billed=int(max_gb * 1024**3),
            labels={"lab": LAB_LABEL, "q": qid, "v": v},
        )
        job = client.query(sql, job_config=cfg)
        if dry_run:
            print(f"{qid} {v:<20} would process {job.total_bytes_processed / 1024**2:>10,.1f} MB")
            continue
        job.result()
        billed = job.total_bytes_billed or 0
        row = {
            "query": qid,
            "variant": v,
            "total_bytes_processed": job.total_bytes_processed,
            "total_bytes_billed": billed,
            "total_slot_ms": job.slot_millis,
            "elapsed_ms": int((job.ended - job.started).total_seconds() * 1000),
            "cost_usd": round(billed / 1024**4 * PRICE_PER_TIB, 6),
            "cache_hit": job.cache_hit,
        }
        rows.append(row)
        print(f"{qid} {v:<20} {row['total_bytes_processed'] / 1024**2:>10,.1f} MB "
              f"{row['total_slot_ms']:>9,} slot-ms {row['elapsed_ms']:>7,} ms")
        time.sleep(0.2)

    if not dry_run:
        with out_path.open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(sorted(rows, key=lambda r: (r["query"], r["variant"])))
        print(f"wrote {out_path.relative_to(ROOT)}")
        report(out_path)


# --------------------------------------------------------------------------- report
def _mb(b: float) -> str:
    mb = b / 1024**2
    return f"{mb:,.0f}" if mb >= 100 else f"{mb:,.1f}"


def report(csv_path: pathlib.Path) -> None:
    data: dict[tuple[str, str], dict] = {}
    for r in csv.DictReader(open(csv_path)):
        data[(r["query"], r["variant"])] = {
            "bytes": float(r["total_bytes_processed"]),
            "billed": float(r["total_bytes_billed"] or 0),
            "slot": float(r["total_slot_ms"] or 0),
            "ms": float(r["elapsed_ms"] or 0),
        }
    names = {qid: name for qid, (name, _) in queries().items()}
    qids = sorted(names)
    base = list(VARIANTS)

    lines = ["# Results", "",
             "All numbers come from real BigQuery jobs (`use_query_cache=false`). "
             "MB = MiB processed (what on-demand billing charges for, before the 10 MB per-table minimum).", "",
             "## Bytes processed (MB)", "",
             "| Query | " + " | ".join(VARIANT_NAMES[v] for v in base) + " | E: MV |",
             "|---|" + "---:|" * (len(base) + 1)]
    for q in qids:
        cells = [_mb(data[(q, v)]["bytes"]) if (q, v) in data else "–" for v in base]
        cells.append(_mb(data[(q, "e_mv")]["bytes"]) if (q, "e_mv") in data else "–")
        lines.append(f"| `{names[q]}` | " + " | ".join(cells) + " |")

    lines += ["", "## Slot time (slot-ms)", "",
              "| Query | " + " | ".join(VARIANT_NAMES[v] for v in base) + " | E: MV |",
              "|---|" + "---:|" * (len(base) + 1)]
    for q in qids:
        cells = [f"{data[(q, v)]['slot']:,.0f}" if (q, v) in data else "–" for v in base]
        cells.append(f"{data[(q, 'e_mv')]['slot']:,.0f}" if (q, "e_mv") in data else "–")
        lines.append(f"| `{names[q]}` | " + " | ".join(cells) + " |")

    # Totals over the queries every base variant ran
    common = [q for q in qids if q not in ANTI_PATTERNS and all((q, v) in data for v in base)]
    if common:
        tot = {v: sum(data[(q, v)]["bytes"] for q in common) for v in base}
        tot_billed = {v: sum(data[(q, v)]["billed"] for q in common) for v in base}
        tot_slot = {v: sum(data[(q, v)]["slot"] for q in common) for v in base}
        lines += ["", f"## Realistic workload (q01-q07, {len(common)} queries; q08/q09 are anti-pattern demos)", "",
                  "| Variant | MB processed | vs A | slot-ms | vs A | $ on-demand |",
                  "|---|---:|---:|---:|---:|---:|"]
        for v in base:
            lines.append(
                f"| {VARIANT_NAMES[v]} | {_mb(tot[v])} | "
                f"{(1 - tot[v] / tot['a_raw']) * 100:.1f}% saved | {tot_slot[v]:,.0f} | "
                f"{(1 - tot_slot[v] / tot_slot['a_raw']) * 100:.1f}% saved | "
                f"${tot_billed[v] / 1024**4 * PRICE_PER_TIB:.5f} |")
        best = min(base, key=lambda v: tot[v])
        lines += ["", f"**Best layout: {VARIANT_NAMES[best]}**, "
                  f"{(1 - tot[best] / tot['a_raw']) * 100:.0f}% fewer bytes and "
                  f"{(1 - tot_bill(tot_billed, best)) * 100:.0f}% lower cost than the unpartitioned table."]

    mv_rows = [(q, data.get((q, "c_part_day_clust")), data.get((q, "e_mv")), data.get((q, "c_after_mv")))
               for q in MV_QUERIES]
    if any(m for _, _, m, _ in mv_rows):
        lines += ["", "## Materialized view", "",
                  "| Query | C before MV (MB) | E: query the MV (MB) | C after MV exists (MB) |",
                  "|---|---:|---:|---:|"]
        for q, c, e, ca in mv_rows:
            f = lambda d: _mb(d["bytes"]) if d else "–"
            lines.append(f"| `{names[q]}` | {f(c)} | {f(e)} | {f(ca)} |")
        lines += ["", "If *C after MV exists* is much smaller than *C before MV*, BigQuery's smart tuning "
                  "rewrote the base-table query to read the MV automatically."]

    pb = data.get(("q09", "c_part_day_clust")), data.get(("q01", "c_part_day_clust"))
    if all(pb):
        lines += ["", "## Partition pruning gotcha", "",
                  f"Same result, same table (C): `q01` filters `creation_date` directly and scans "
                  f"**{_mb(pb[1]['bytes'])} MB**; `q09` wraps it in `FORMAT_TIMESTAMP()` and scans "
                  f"**{_mb(pb[0]['bytes'])} MB** ({pb[0]['bytes'] / pb[1]['bytes']:.0f}x more)."]

    RESULTS.mkdir(exist_ok=True)
    (RESULTS / "results.md").write_text("\n".join(lines) + "\n")
    print("wrote results/results.md")
    chart(data, names, qids)


def tot_bill(tot_billed: dict, v: str) -> float:
    return tot_billed[v] / tot_billed["a_raw"] if tot_billed["a_raw"] else 1.0


def chart(data, names, qids) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    series = list(VARIANTS) + ["e_mv"]
    series = [s for s in series if any((q, s) in data for q in qids)]
    fig, ax = plt.subplots(figsize=(11, 5.2), dpi=160)
    fig.patch.set_facecolor("#fcfcfb")
    ax.set_facecolor("#fcfcfb")
    x = np.arange(len(qids))
    w = 0.8 / len(series)
    for i, s in enumerate(series):
        ys = [data[(q, s)]["bytes"] / 1024**2 if (q, s) in data else np.nan for q in qids]
        ax.bar(x - 0.4 + w * (i + 0.5), ys, w * 0.88, color=COLORS[s], label=VARIANT_NAMES[s],
               edgecolor="#fcfcfb", linewidth=1)
    ax.set_yscale("log")
    ax.set_xticks(x, [names[q].split("_", 1)[1].replace("_", " ") for q in qids],
                  rotation=25, ha="right", fontsize=9, color="#52514e")
    ax.set_ylabel("MB processed (log scale)", color="#52514e")
    ax.set_title("Bytes scanned per query, by table design (lower is cheaper)",
                 loc="left", fontsize=12, color="#0b0b0b")
    ax.grid(axis="y", color="#e6e5e0", linewidth=0.6)
    ax.set_axisbelow(True)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)
    for sp in ("left", "bottom"):
        ax.spines[sp].set_color("#c3c2b7")
    ax.tick_params(colors="#52514e")
    ax.legend(frameon=False, fontsize=8.5, ncol=3, loc="upper left", bbox_to_anchor=(0, -0.28))
    fig.tight_layout()
    fig.savefig(RESULTS / "bytes_scanned.png", facecolor=fig.get_facecolor())
    print("wrote results/bytes_scanned.png")


# --------------------------------------------------------------------------- cli
def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--project", required=True)
    r.add_argument("--phase", choices=["base", "mv"], default="base")
    r.add_argument("--max-gb", type=float, default=5.0, help="per-query maximum_bytes_billed cap")
    r.add_argument("--dry-run", action="store_true", help="estimate bytes only, run nothing")
    r.add_argument("--shift-years", type=int, default=SANDBOX_SHIFT_YEARS, help="must match the value used to build tables")
    e = sub.add_parser("emit")
    e.add_argument("--shift-years", type=int, default=SANDBOX_SHIFT_YEARS,
                   help=f"use {SANDBOX_SHIFT_YEARS} in the BigQuery sandbox (partition expiry workaround)")
    rep = sub.add_parser("report")
    rep.add_argument("csv", type=pathlib.Path)
    a = ap.parse_args(argv)
    if a.cmd == "run":
        run(a.project, a.phase, a.max_gb, a.dry_run, a.shift_years)
    elif a.cmd == "emit":
        emit(a.shift_years)
    else:
        report(a.csv)


if __name__ == "__main__":
    sys.exit(main())
